version: '3.9'
services:
    postgres:
        image: postgres:13.3
        restart: always
        environment:
          #POSTGRES_DB=restapi_dev
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          #USERMAP_UID=999
          #USERMAP_GID=999
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          # ./db/migrations/000001_create_transfers_users_table.sql:/docker-entrypoint-initdb.d/000001_create_transfers_user_table.sql
          # ./db/migrations/000002_add_transfers_check_constraints.sql:/docker-entrypoint-initdb.d/000002_add_transfers_check_constraints.sql