port = 4000 #API Server port
env = "development" #Environment (development|staging|production)

[db]
dsn = "postgres://wallet:pa55word@localhost/wallet?sslmode=disable" #PostgreSQL DSN
maxOpenConns = 25 #PostgreSQL max open connections
maxIdleConns = 25 #PostgreSQL max idle connections
maxIdleTime = "15m" #PostgreSQL max connection idle time
